#!/bin/sh /etc/rc.common

USE_PROCD=1
START=15

create_ipset() { 
	local SET_NAME="$1"
	procd_open_instance "fdf-ipset-$SET_NAME"
	procd_set_param command ipset -exist create "$SET_NAME" hash:ip,port timeout 0 hashsize 64
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	config_load fdf
	config_foreach create_ipset ipset
}
